---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: NetApp生成AI驱动的助手文档可从docs.ocs.com获得NetApp。DOC仅使用此站点上发布的内容来回答有关NetApp产品的问题。DOC不使用其他NetApp站点或公共互联网上的内容来回答问题。 
---
= NetApp生成型AI驱动的助手概述
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
由NetApp生成的AI驱动的助手"Doc"可从NetApp．com获得。DOC仅使用此站点上发布的内容来回答有关NetApp产品的问题。DOC不使用其他NetApp站点或公共互联网上的内容来回答问题。



== 功能

* DOC不是大象，而是有着相当的回忆。
+
大多数情况下、Doc都会记住并关注您正在讨论的内容。如果Doc无法跟踪某个对话，您可以在同一个文本交谈会话中启动一个新的对话。

* Doc是一位非常有读者的人。
+
每当我们的文档在docs.netapp.com上发布时(这种情况很多)、Doc都会读取并引用这些文档以生成其响应。Doc学习的速度令人惊叹。

* DOC是顾问式的。
+
除了您提出的问题之外、DOC还会为您可能需要提出的问题提供建议。

* DOC是沟通性的。
+
DOC分享了有关其如何生成回复的见解、让您有机会重新表述您的问题。





== 限制

* DOC仅使用docs.docs.com.com上发布的内容NetApp生成答案。DOC不会从其他NetApp网站上发布的内容生成答案。
* 在测试期间、文档并不会参考所有NetApp产品的所有文档。DOC仅指部分文档、包括但不限于ONTAP、BlueXP 、StorageGRID、Keystone和SnapCenter文档、以帮助您找到答案。如果您要查找文档不知道的信息、请发送电子邮件至：ng) doccoments@NetApp．com[告诉我们]。
* 如果NetApp产品具有多个版本的文档、则文档仅引用最新版本来帮助生成答案。
* DOC不会参考您所在的页面来假设您感兴趣的产品。请尽可能具体地回答您的问题、并提及产品名称和版本。
* 虽然文档可以提供其他语言的回复、但文档尚未阅读非英语版本的NetApp产品文档。为确保您获得尽可能准确的信息、请始终以英语验证文档的回答。




== 提示

* DOC喜欢特定问题。
+
当您明确引用产品名称、界面(例如GUI或API)和版本时、DOC可提供更好的响应。例如：_System Manager中应执行哪些步骤才能从ONTAP 9.8升级到ONTAP 9.12.1？_

* 需要了解如何做一些事情？
+
考虑让文档包含这些步骤。不要问文档_如何在不使用互联网的情况下安装BlueXP  连接器？_请尝试询问_在不使用互联网的情况下安装BlueXP  连接器应遵循哪些步骤？_

* 提出简单的问题。
+
如果您需要提出一个复杂的问题、请将其细分为几个小问题(这有时称为连锁式问题)。在聊天会话期间、Doc会注意并记住您提出的问题。

+
不要问Doc _如何在BlueXP  中配置勒索软件保护和备份计划？_尝试_在BlueXP  中配置勒索软件保护的步骤是什么？_和_在BlueXP  中配置备份计划的步骤是什么？_

* 使用引号澄清您希望Doc注意Doc可能会误解的多字短语的情况。
+
例如、如果您询问Doc _how is storage 킧 싊 calculated in ONTAP？_、那么可能Doc会认为您是在问两个不相关的词语、即存储和效率。为了确保Doc了解您询问的是(称为概念)存储效率、请将该短语用引号括起来、如下所示：_how is "storage 킧 싊" calculated in ONTAP？_

+
如果您正在与人交谈、您可能会强调这句话、可能会使用空引号、或以某种方式表明区别的姿态。将双引号视为有助于Doc了解您所说内容的一种姿态。

* 回复后、Doc将提供有关其响应生成方式的见解。保持好奇心。
+
尝试不同的提问方式和方法。如果您未获得所需的结果、请尝试改写您的问题。





== 反馈

我们正在努力不断改进Doc.请在Doc的聊天窗口内向我们发送反馈。如果Doc的回答准确且有用、或者不完整或不充分、请告知我们。如果您对Doc的能力或回复有任何疑问或顾虑、也可以发送电子邮件至：ng-doccoments@netapp.com [联系我们]。
