---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: doc是docs.ap.dom上提供的NetApp AI助手NetApp。它仅使用此站点中的内容来回答问题。DOC不使用其他NetApp站点或公共互联网上的内容来回答问题。 
---
= NetApp生成型AI驱动的助手概述
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
doc是docs.ap.dom上提供的NetApp AI助手NetApp。它仅使用此站点中的内容来回答问题。DOC不使用其他NetApp站点或公共互联网上的内容来回答问题。

DOC可以根据以前的问题构建答案、建议其他问题、并说明如何生成答案。这使其成为浏览NetApp文档的宝贵工具。



== 范围和限制

DOC只能根据docs.docs.com上发布的精选内容回答问题NetApp。


NOTE: 在此测试阶段、文档不会针对所有docs.docs.com.com NetApp内容进行培训。DOC可以回答有关内容的问题、包括但不限于ONTAP、BlueXP 、StorageGRID、Keystone和SnapCenter内容。如果您需要文档没有的信息、请告知我们。

* 如果未指定产品版本、Doc将根据最新发布的版本回答问题。如果需要、您可以在问题中指定早期版本。
* 当您提出问题时、DOC不知道您所在的页面。为了获得最佳效果、请具体说明产品名称和版本。
* DOC可以使用docs.docs.com.com上支持的语言进行聊天NetApp、但未接受非英语版本的培训。




== 编写良好的提示

请按照以下提示操作、以获得最佳的Doc体验。

提出具体问题。:: 编写详细的问题并指定产品名称、版本和接口类型(GUI、API)。例如：
+
--
[]
====
要从ONTAP 9.8升级到ONTAP 9.12.1、应在System Manager中执行哪些步骤？

====
--
询问完成任务的步骤。:: 要求文档包含完成流程的步骤。而不是询问_如何在没有互联网的情况下安装BlueXP  连接器？_尝试：
+
--
[]
====
在不使用互联网的情况下安装BlueXP  连接器应遵循哪些步骤？

====
--
将复杂的问题分成若干个部分。:: 将复杂的问题细分为小问题(也称为_challch_)。DOC会记住之前的问题、并在您继续聊天时提供更复杂的答案。
+
--
例如、请不要询问Doc _如何在BlueXP  中配置勒索软件保护和备份计划？_、而是尝试：

[]
====
在BlueXP  中配置勒索软件保护的步骤是什么？

====
然后询问：

[]
====
在BlueXP  中配置备份计划的步骤是什么？

====
--
使用引号。:: 用引号将多字短语括起来。这有助于Doc将该短语识别为一个概念、类似于您在与人的对话中强调它的方式。
+
--
例如、在这个问题中、_如何在ONTAP？_文档中计算存储效率？_文档可能会认为您是在询问_storage_和_效率_这两个不相关的词。请尝试：

[]
====
如何在ONTAP中计算"存储效率"？

====
--
查看文档的响应方式。:: 回复后、Doc将提供有关其响应生成方式的见解。这可以为您提供有关如何细化问题以获得所需结果的想法。
清除聊天历史记录:: 如果要更改主题、请在开始时清除聊天。由于Doc会记住之前的问题、因此主题更改可能会产生意外结果。




== 反馈

您的反馈有助于我们改进Doc的响应方式。使用文档聊天窗口中的反馈工具告知我们答案是否准确、有用、或者是否需要改进。您也可以发送电子邮件至：ng)注释@NetApp．com[与我们联系](如有问题或反馈)。
