---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: DOC是我们在docs.netapp.com上提供的由人工智能驱动的生成性助手。DOC旨在使用docs.docs.com上发布的内容来回答有关NetApp产品的问题NetApp。 
---
= NetApp生成型AI驱动的助手概述
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOC是我们在docs.netapp.com上提供的由人工智能驱动的生成性助手。DOC旨在使用docs.docs.com上发布的内容来回答有关NetApp产品的问题NetApp。

DOC可以根据以前的问题构建答案、建议其他问题、并说明如何生成答案。这使其成为浏览NetApp文档的宝贵工具。



== 范围和限制

DOC只能根据docs.docs.com上发布的精选内容回答问题NetApp。


NOTE: 在 Beta 阶段，Doc 会使用 docs.netapp.com 上发布的大部分（但并非全部）内容来回答问题。Doc熟悉所有ONTAP、 BlueXP、 StorageGRID、E 系列、 Keystone和SnapCenter文档，并使用它们来回答有关这些产品的问题。另一方面，Doc 并不熟悉某些旧版产品的文档。例如，Doc 不使用SnapDrive for UNIX文档来提供答案。在整个 Beta 阶段，我们都在努力完善 Doc 的知识。如果您需要 Doc 所没有的信息，请发送电子邮件至 mailto:ng-doccomments@netapp.com[告知我们]。

* Doc 仅根据产品最新发布的版本回答问题。例如，如果产品有 1.0 版和 2.0 版的文档，Doc 仅参考最新的 2.0 版文档。
* 为了获得最佳效果，请务必使用具体的产品名称。Doc知道您提问时在哪个页面，但这只是 Doc 在制定答案时考虑的几个因素之一。
* DOC可以使用docs.docs.com.com上支持的语言进行聊天NetApp、但未接受非英语版本的培训。




== 编写良好的提示

请按照以下提示操作、以获得最佳的Doc体验。

提出具体问题。:: 编写详细的问题并指定产品名称、版本和接口类型(GUI、API)。例如：
+
--
[]
====
要从ONTAP 9.8升级到ONTAP 9.12.1、应在System Manager中执行哪些步骤？

====
--
询问完成任务的步骤。:: 要求文档包含完成流程的步骤。而不是询问_如何在没有互联网的情况下安装BlueXP  连接器？_尝试：
+
--
[]
====
在不使用互联网的情况下安装BlueXP  连接器应遵循哪些步骤？

====
--
将复杂的问题分成若干个部分。:: 将复杂的问题细分为小问题(也称为_challch_)。DOC会记住之前的问题、并在您继续聊天时提供更复杂的答案。
+
--
例如、请不要询问Doc _如何在BlueXP  中配置勒索软件保护和备份计划？_、而是尝试：

[]
====
在BlueXP  中配置勒索软件保护的步骤是什么？

====
然后询问：

[]
====
在BlueXP  中配置备份计划的步骤是什么？

====
--
使用引号。:: 用引号将多字短语括起来。这有助于Doc将该短语识别为一个概念、类似于您在与人的对话中强调它的方式。
+
--
例如、在这个问题中、_如何在ONTAP？_文档中计算存储效率？_文档可能会认为您是在询问_storage_和_效率_这两个不相关的词。请尝试：

[]
====
如何在ONTAP中计算"存储效率"？

====
--
查看文档的响应方式。:: 回复后、Doc将提供有关其响应生成方式的见解。这可以为您提供有关如何细化问题以获得所需结果的想法。
清除聊天历史记录:: 如果您想更改主题（例如，想询问其他产品），请清除聊天记录以开始新的会话。如果您在开始新主题之前没有清除聊天记录，可能会得到不准确的结果。




== 反馈

我们正在努力不断改进Doc.请在Doc的聊天窗口内向我们发送反馈。如果Doc的回答准确且有用、或者不完整或不充分、请告知我们。如果您对NetApp的能力或回复有任何疑问或顾虑、也可以发送电子邮件至：ng—doccomments@Doc.com[联系我们]。
