---
sidebar: sidebar 
permalink: docs-netapp-com.html 
keywords:  
summary:  
---
= 关于docs.netapp.com站点
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


.站点导览
video::77a636ba-4202-45bb-9e47-b08a01138502[panopto]
.文字记录
[%collapsible]
====
0：01:: 你(们)好。我是来自docs.netapp.com团队的Ben。在本视频中、我们将介绍docs.netapp.com上提供的特性和功能、帮助您充分利用内容观看体验。
0：12:: 让我们从查找您要查找的内容开始。输入文档网站后、您可以使用网站左侧进行导航。
0：20:: 如果文档有多个版本、您可以为所使用的产品版本选择相应的文档。
0：28:: 使用搜索框在文档站点中查找内容。例如、我想了解卷加密的工作原理。
0：36:: 如果您更喜欢浏览文档、则可以使用目录、该目录按逻辑分组进行组织、例如入门和产品使用。
0：45:: 如果要转到另一个文档站点、可以使用导航点浏览docs.netapp.com。
0：50:: 找到要查找的内容后、您可以使用一些关键功能来帮助您与内容进行交互。
0：58:: 大多数文档站点都提供多种不同的语言版本、因此您可以使用首选语言阅读文档。
1：05:: 如果一个页面包含多个部分、您可以使用"在此页面上"链接直接转到所需的内容。这些链接还会标识您在页面上的位置、这有助于您在滚动时跟踪页面。
1：20:: 要仅关注内容本身、您可以折叠左侧和右侧边栏。完成后、展开它们以再次查看导航控件。
1时33分:: 如果您需要脱机阅读文档、可以下载整个文档网站或网站中各个部分的PDF。
1时41分:: NetApp文档是开源文档、旨在允许使用GitHub帐户进行社区贡献。提交您的反馈以请求更新文档或直接自行编辑内容、这些内容会在合并前提交给NetApp内容主管。
1时59分:: 在我们某些云服务的文档站点上、您可能会看到一个云提供商选项、可用于根据特定云提供商筛选文档。例如、如果您选择Microsoft Azure、则只会看到适用场景Azure的内容。其他云提供商的内容不会显示。
2时18分:: 由于您可能会从平板电脑、移动设备或桌面访问我们的内容、因此我们会使用响应式布局来确保文档在任何设备上都能正常显示。
2时28分:: 就是这样。我们希望您喜欢使用这些功能、并感谢您加入我们的内容社区。


====